name-template: 'v$RESOLVED_VERSION'  # Will be replaced by the version from the tag
tag-template: 'v$RESOLVED_VERSION'   # Will be replaced by the version from the tag
categories:
  - title: ' Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: ' Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: ' Maintenance'
    label: 'chore'
  - title: ' Documentation'
    label: 'documentation'
  - title: ' Tests'
    label: 'test'
  - title: ' Dependencies'
    label: 'dependencies'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: "\\`*_#"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## What's Changed
  $CHANGES

  **Full Changelog**: $PREVIOUS_TAG...$RESOLVED_VERSION

  ## Code Diffs
  $DIFFS
